//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_06_MusicCollection.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О рекламе.
        /// </summary>
        public static string AboutAdsLink {
            get {
                return ResourceManager.GetString("AboutAdsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступность.
        /// </summary>
        public static string AccessibilityLink {
            get {
                return ResourceManager.GetString("AccessibilityLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реклама.
        /// </summary>
        public static string Advertising {
            get {
                return ResourceManager.GetString("Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбом.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщества.
        /// </summary>
        public static string Communities {
            get {
                return ResourceManager.GetString("Communities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки файлов cookie.
        /// </summary>
        public static string CookieSettingsLink {
            get {
                return ResourceManager.GetString("CookieSettingsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы cookie.
        /// </summary>
        public static string CookiesLink {
            get {
                return ResourceManager.GetString("CookiesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создайте свой первый плейлист.
        /// </summary>
        public static string CreateFirstPlaylist {
            get {
                return ResourceManager.GetString("CreateFirstPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать плейлист.
        /// </summary>
        public static string CreatePlaylistButton {
            get {
                return ResourceManager.GetString("CreatePlaylistButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать плейлист.
        /// </summary>
        public static string CreatePlaylistTooltip {
            get {
                return ResourceManager.GetString("CreatePlaylistTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для разработчиков.
        /// </summary>
        public static string Developers {
            get {
                return ResourceManager.GetString("Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это легко, мы вам поможем.
        /// </summary>
        public static string EasyDescription {
            get {
                return ResourceManager.GetString("EasyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для артистов.
        /// </summary>
        public static string For_Artists {
            get {
                return ResourceManager.GetString("For_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Официальная информация.
        /// </summary>
        public static string For_the_Record {
            get {
                return ResourceManager.GetString("For_the_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильное прил..
        /// </summary>
        public static string Free_Mobile_App {
            get {
                return ResourceManager.GetString("Free_Mobile_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string HomeLink {
            get {
                return ResourceManager.GetString("HomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвесторам.
        /// </summary>
        public static string Investors {
            get {
                return ResourceManager.GetString("Investors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансии.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правовая информация.
        /// </summary>
        public static string LegalLink {
            get {
                return ResourceManager.GetString("LegalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string ManagementLink {
            get {
                return ResourceManager.GetString("ManagementLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плейлист.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Pr_Head {
            get {
                return ResourceManager.GetString("Pr_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык - Изменения вступят в силу после перезапуска приложения.
        /// </summary>
        public static string Pr_LangDesc {
            get {
                return ResourceManager.GetString("Pr_LangDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Pr_LangHead {
            get {
                return ResourceManager.GetString("Pr_LangHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премиум (2 пол.).
        /// </summary>
        public static string Premium_Duo {
            get {
                return ResourceManager.GetString("Premium_Duo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премиум (семейный).
        /// </summary>
        public static string Premium_Family {
            get {
                return ResourceManager.GetString("Premium_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премиум (1 пол.).
        /// </summary>
        public static string Premium_Individual {
            get {
                return ResourceManager.GetString("Premium_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премиум (студент.).
        /// </summary>
        public static string Premium_Student {
            get {
                return ResourceManager.GetString("Premium_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Политика конфиденциальности.
        /// </summary>
        public static string PrivacyPolicyLink {
            get {
                return ResourceManager.GetString("PrivacyPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центр безопасности и конфиденциальности.
        /// </summary>
        public static string SafetyPrivacyLink {
            get {
                return ResourceManager.GetString("SafetyPrivacyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string SearchLink {
            get {
                return ResourceManager.GetString("SearchLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать все.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Песни не найдены.
        /// </summary>
        public static string SongsNotFound {
            get {
                return ResourceManager.GetString("SongsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify бесплатно.
        /// </summary>
        public static string Spotify_Free {
            get {
                return ResourceManager.GetString("Spotify_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарифы Spotify.
        /// </summary>
        public static string Spotify_Plans {
            get {
                return ResourceManager.GetString("Spotify_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего лайков.
        /// </summary>
        public static string TotalLikes {
            get {
                return ResourceManager.GetString("TotalLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего песен.
        /// </summary>
        public static string TotalSongs {
            get {
                return ResourceManager.GetString("TotalSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полезные ссылки.
        /// </summary>
        public static string Useful_links {
            get {
                return ResourceManager.GetString("Useful_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставщикам.
        /// </summary>
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать,.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша библиотека.
        /// </summary>
        public static string YourLibrary {
            get {
                return ResourceManager.GetString("YourLibrary", resourceCulture);
            }
        }
    }
}
